/**
 * KASUWA 2.0 — Marketplace Data
 * Product catalog, categories, seller profiles, and sample data for the AI-driven night market
 */

export interface Seller {
  id: string;
  name: string;
  shopName: string;
  phone: string;
  whatsapp: string;
  email: string;
  address: string;
  city: string;
  state: string;
  lga: string;
  landmark: string;
  shopType: "market_stall" | "shop" | "warehouse" | "home_business" | "office" | "online";
  verified: boolean;
  rating: number;
  totalSales: number;
  joinedDate: string;
  avatar: string;
}

export interface Product {
  id: string;
  name: string;
  category: string;
  subcategory: string;
  price: number;
  currency: string;
  condition: string;
  state: string;
  seller: string;
  sellerId: string;
  sellerDetails?: Seller;
  image: string;
  description: string;
  specs: Record<string, string>;
  negotiable: boolean;
  haggleRange: { min: number; max: number };
  communityDeal?: {
    minBuyers: number;
    discountPercent: number;
    currentBuyers: number;
  };
  postedAt: string;
  views: number;
}

export interface CartItem {
  product: Product;
  quantity: number;
  agreedPrice: number;
}

// ── Seller Database ──

export const SELLERS: Record<string, Seller> = {
  "seller-1": {
    id: "seller-1",
    name: "Alhaji Ibrahim Musa",
    shopName: "Alhaji Motors",
    phone: "+234 803 456 7890",
    whatsapp: "+2348034567890",
    email: "alhaji.motors@gmail.com",
    address: "45 Oshodi-Apapa Expressway, Ladipo Spare Parts Market",
    city: "Lagos",
    state: "Lagos",
    lga: "Oshodi-Isolo",
    landmark: "Opposite Ladipo Bus Stop, near First Bank",
    shopType: "warehouse",
    verified: true,
    rating: 4.8,
    totalSales: 342,
    joinedDate: "2023-03-15",
    avatar: "🏪",
  },
  "seller-2": {
    id: "seller-2",
    name: "Chief Adebayo Ogundimu",
    shopName: "Capital Auto",
    phone: "+234 805 678 1234",
    whatsapp: "+2348056781234",
    email: "capital.auto@yahoo.com",
    address: "12 Aminu Kano Crescent, Wuse 2",
    city: "Abuja",
    state: "FCT",
    lga: "Municipal Area Council",
    landmark: "Next to Sheraton Hotel, Wuse Zone 2",
    shopType: "shop",
    verified: true,
    rating: 4.6,
    totalSales: 189,
    joinedDate: "2023-06-20",
    avatar: "🏗️",
  },
  "seller-3": {
    id: "seller-3",
    name: "Chinedu Eze",
    shopName: "TechZone NG",
    phone: "+234 701 234 5678",
    whatsapp: "+2347012345678",
    email: "techzone.ng@gmail.com",
    address: "Block B, Shop 14, Computer Village, Ikeja",
    city: "Lagos",
    state: "Lagos",
    lga: "Ikeja",
    landmark: "Inside Computer Village, beside Otigba Street entrance",
    shopType: "shop",
    verified: true,
    rating: 4.9,
    totalSales: 1205,
    joinedDate: "2022-11-01",
    avatar: "📱",
  },
  "seller-4": {
    id: "seller-4",
    name: "Adewale Ogunleye",
    shopName: "iStore Computer Village",
    phone: "+234 806 789 0123",
    whatsapp: "+2348067890123",
    email: "istore.cv@gmail.com",
    address: "15 Otigba Street, Computer Village, Ikeja",
    city: "Lagos",
    state: "Lagos",
    lga: "Ikeja",
    landmark: "Opposite GSM Village, Computer Village",
    shopType: "shop",
    verified: true,
    rating: 4.7,
    totalSales: 890,
    joinedDate: "2022-08-14",
    avatar: "📲",
  },
  "seller-5": {
    id: "seller-5",
    name: "Fatima Abubakar",
    shopName: "ElectroHub",
    phone: "+234 807 234 5678",
    whatsapp: "+2348072345678",
    email: "electrohub.abj@gmail.com",
    address: "8 Adetokunbo Ademola Crescent, Wuse 2",
    city: "Abuja",
    state: "FCT",
    lga: "Municipal Area Council",
    landmark: "Beside Wuse Market, Gate 2",
    shopType: "shop",
    verified: true,
    rating: 4.5,
    totalSales: 445,
    joinedDate: "2023-01-10",
    avatar: "📺",
  },
  "seller-6": {
    id: "seller-6",
    name: "Barrister Kemi Adeosun",
    shopName: "Prime Properties NG",
    phone: "+234 802 345 6789",
    whatsapp: "+2348023456789",
    email: "prime.properties@yahoo.com",
    address: "Suite 302, Admiralty Way Plaza, Lekki Phase 1",
    city: "Lagos",
    state: "Lagos",
    lga: "Eti-Osa",
    landmark: "Opposite Lekki Conservation Centre",
    shopType: "office",
    verified: true,
    rating: 4.4,
    totalSales: 78,
    joinedDate: "2023-05-22",
    avatar: "🏠",
  },
  "seller-7": {
    id: "seller-7",
    name: "Mama Halima",
    shopName: "Aso Oke Palace",
    phone: "+234 808 456 7890",
    whatsapp: "+2348084567890",
    email: "",
    address: "Stall 23, Balogun Market, Lagos Island",
    city: "Lagos",
    state: "Lagos",
    lga: "Lagos Island",
    landmark: "Inside Balogun Market, textile section, 3rd row",
    shopType: "market_stall",
    verified: true,
    rating: 4.8,
    totalSales: 2340,
    joinedDate: "2022-05-01",
    avatar: "👗",
  },
  "seller-8": {
    id: "seller-8",
    name: "Malam Yunusa",
    shopName: "Chief Tailor",
    phone: "+234 809 567 8901",
    whatsapp: "+2348095678901",
    email: "",
    address: "45 Adetokunbo Ademola Crescent, Wuse 2",
    city: "Abuja",
    state: "FCT",
    lga: "Municipal Area Council",
    landmark: "Beside NAFDAC office, Wuse Zone 2",
    shopType: "shop",
    verified: false,
    rating: 4.3,
    totalSales: 567,
    joinedDate: "2023-09-10",
    avatar: "👔",
  },
  "seller-9": {
    id: "seller-9",
    name: "Tunde Bakare",
    shopName: "HomeFitters NG",
    phone: "+234 702 678 9012",
    whatsapp: "+2347026789012",
    email: "homefitters@gmail.com",
    address: "15 Allen Avenue, Ikeja",
    city: "Lagos",
    state: "Lagos",
    lga: "Ikeja",
    landmark: "Beside Zenith Bank, Allen Avenue roundabout",
    shopType: "warehouse",
    verified: true,
    rating: 4.6,
    totalSales: 312,
    joinedDate: "2023-02-28",
    avatar: "🛋️",
  },
  "seller-10": {
    id: "seller-10",
    name: "Chioma Nwosu",
    shopName: "Crown Hair Gallery",
    phone: "+234 703 789 0123",
    whatsapp: "+2347037890123",
    email: "crown.hair@gmail.com",
    address: "Shop 7, Maryland Mall, Ikorodu Road",
    city: "Lagos",
    state: "Lagos",
    lga: "Kosofe",
    landmark: "Maryland Mall, ground floor, near entrance",
    shopType: "shop",
    verified: true,
    rating: 4.9,
    totalSales: 1876,
    joinedDate: "2022-07-15",
    avatar: "💇",
  },
  "seller-11": {
    id: "seller-11",
    name: "Master Emeka",
    shopName: "Master Plumbers NG",
    phone: "+234 704 890 1234",
    whatsapp: "+2347048901234",
    email: "master.plumbers@gmail.com",
    address: "22 Mowe Street, Ojodu Berger",
    city: "Lagos",
    state: "Lagos",
    lga: "Ikeja",
    landmark: "Near Ojodu Berger bus terminal",
    shopType: "home_business",
    verified: true,
    rating: 4.5,
    totalSales: 234,
    joinedDate: "2023-04-18",
    avatar: "🔧",
  },
  "seller-12": {
    id: "seller-12",
    name: "Alhaji Sani Bello",
    shopName: "GreenFarm Agro",
    phone: "+234 805 901 2345",
    whatsapp: "+2348059012345",
    email: "greenfarm.agro@gmail.com",
    address: "KM 12, Ibadan-Lagos Expressway, Moniya",
    city: "Ibadan",
    state: "Oyo",
    lga: "Akinyele",
    landmark: "Moniya Farm Settlement, opposite NNPC station",
    shopType: "warehouse",
    verified: true,
    rating: 4.7,
    totalSales: 567,
    joinedDate: "2023-01-05",
    avatar: "🌾",
  },
  "seller-13": {
    id: "seller-13",
    name: "Mama Calabar",
    shopName: "Mama Calabar Kitchen",
    phone: "+234 806 012 3456",
    whatsapp: "+2348060123456",
    email: "",
    address: "15 Bode Thomas Street, Surulere",
    city: "Lagos",
    state: "Lagos",
    lga: "Surulere",
    landmark: "Opposite ShopRite, Bode Thomas",
    shopType: "home_business",
    verified: false,
    rating: 4.9,
    totalSales: 3456,
    joinedDate: "2022-03-20",
    avatar: "🍲",
  },
  "seller-14": {
    id: "seller-14",
    name: "Dele Ogun",
    shopName: "SportsHub NG",
    phone: "+234 707 123 4567",
    whatsapp: "+2347071234567",
    email: "sportshub.ng@gmail.com",
    address: "34 Allen Avenue, Ikeja",
    city: "Lagos",
    state: "Lagos",
    lga: "Ikeja",
    landmark: "Beside Ikeja City Mall back entrance",
    shopType: "shop",
    verified: true,
    rating: 4.4,
    totalSales: 890,
    joinedDate: "2023-03-12",
    avatar: "⚽",
  },
  "seller-15": {
    id: "seller-15",
    name: "Mrs. Aisha Ibrahim",
    shopName: "BabyWorld NG",
    phone: "+234 808 234 5678",
    whatsapp: "+2348082345678",
    email: "babyworld.ng@gmail.com",
    address: "Shop 12, The Palms Shopping Mall, Lekki",
    city: "Lagos",
    state: "Lagos",
    lga: "Eti-Osa",
    landmark: "The Palms Mall, 2nd floor, kids section",
    shopType: "shop",
    verified: true,
    rating: 4.8,
    totalSales: 1234,
    joinedDate: "2022-09-01",
    avatar: "👶",
  },
  "seller-16": {
    id: "seller-16",
    name: "Emeka Okoro",
    shopName: "PhoneHub NG",
    phone: "+234 709 345 6789",
    whatsapp: "+2347093456789",
    email: "phonehub.ng@gmail.com",
    address: "Block C, Shop 8, Computer Village, Ikeja",
    city: "Lagos",
    state: "Lagos",
    lga: "Ikeja",
    landmark: "Inside Computer Village, near Peacock Street",
    shopType: "shop",
    verified: true,
    rating: 4.6,
    totalSales: 2345,
    joinedDate: "2022-06-15",
    avatar: "📱",
  },
  "seller-17": {
    id: "seller-17",
    name: "Aminu Garba",
    shopName: "GadgetPoint",
    phone: "+234 801 456 7890",
    whatsapp: "+2348014567890",
    email: "gadgetpoint@gmail.com",
    address: "45 Ahmadu Bello Way, Area 10, Garki",
    city: "Abuja",
    state: "FCT",
    lga: "Garki",
    landmark: "Beside Garki Market, Area 10",
    shopType: "shop",
    verified: false,
    rating: 4.2,
    totalSales: 456,
    joinedDate: "2023-07-20",
    avatar: "📲",
  },
  "seller-18": {
    id: "seller-18",
    name: "Blessing Okafor",
    shopName: "AccessoryZone",
    phone: "+234 802 567 8901",
    whatsapp: "+2348025678901",
    email: "accessoryzone@gmail.com",
    address: "Stall 45, Computer Village, Ikeja",
    city: "Lagos",
    state: "Lagos",
    lga: "Ikeja",
    landmark: "Computer Village, accessories row",
    shopType: "market_stall",
    verified: true,
    rating: 4.5,
    totalSales: 3421,
    joinedDate: "2022-04-10",
    avatar: "🔌",
  },
  "seller-19": {
    id: "seller-19",
    name: "Malam Usman Dantata",
    shopName: "Kano Leather Works",
    phone: "+234 803 678 9012",
    whatsapp: "+2348036789012",
    email: "kano.leather@gmail.com",
    address: "Kurmi Market, Emir Palace Road, Kano",
    city: "Kano",
    state: "Kano",
    lga: "Municipal",
    landmark: "Inside Kurmi Market, leather section, near North Gate",
    shopType: "market_stall",
    verified: true,
    rating: 4.9,
    totalSales: 1567,
    joinedDate: "2022-01-15",
    avatar: "👜",
  },
  "seller-20": {
    id: "seller-20",
    name: "Aunty Bimpe",
    shopName: "Aunty Zobo",
    phone: "+234 804 789 0123",
    whatsapp: "+2348047890123",
    email: "",
    address: "5 Opebi Road, Ikeja",
    city: "Lagos",
    state: "Lagos",
    lga: "Ikeja",
    landmark: "Near Opebi roundabout, beside filling station",
    shopType: "home_business",
    verified: false,
    rating: 4.7,
    totalSales: 5678,
    joinedDate: "2022-02-01",
    avatar: "🥤",
  },
  "seller-21": {
    id: "seller-21",
    name: "Engineer Femi",
    shopName: "PowerTech NG",
    phone: "+234 805 890 1234",
    whatsapp: "+2348058901234",
    email: "powertech.ng@gmail.com",
    address: "12 Oregun Road, Ojota",
    city: "Lagos",
    state: "Lagos",
    lga: "Kosofe",
    landmark: "Beside Ojota Motor Park, Kudirat Abiola Way",
    shopType: "warehouse",
    verified: true,
    rating: 4.4,
    totalSales: 234,
    joinedDate: "2023-04-01",
    avatar: "⚡",
  },
  "seller-22": {
    id: "seller-22",
    name: "Ngozi Eze",
    shopName: "GlowUp Beauty",
    phone: "+234 706 901 2345",
    whatsapp: "+2347069012345",
    email: "glowup.beauty@gmail.com",
    address: "Shop 23, Ikeja City Mall, Alausa",
    city: "Lagos",
    state: "Lagos",
    lga: "Ikeja",
    landmark: "Ikeja City Mall, ground floor, beauty wing",
    shopType: "shop",
    verified: true,
    rating: 4.6,
    totalSales: 1890,
    joinedDate: "2023-02-14",
    avatar: "💄",
  },
  "seller-23": {
    id: "seller-23",
    name: "DJ SoundMax",
    shopName: "DJ SoundMax",
    phone: "+234 807 012 3456",
    whatsapp: "+2348070123456",
    email: "dj.soundmax@gmail.com",
    address: "3 Allen Avenue, Ikeja",
    city: "Lagos",
    state: "Lagos",
    lga: "Ikeja",
    landmark: "Above First Bank, Allen Avenue",
    shopType: "home_business",
    verified: true,
    rating: 4.8,
    totalSales: 567,
    joinedDate: "2023-05-30",
    avatar: "🎵",
  },
  "seller-24": {
    id: "seller-24",
    name: "Alhaji Abdulsalam",
    shopName: "Savanna Farms",
    phone: "+234 808 123 4567",
    whatsapp: "+2348081234567",
    email: "savanna.farms@gmail.com",
    address: "Dawanau International Grains Market, Kano",
    city: "Kano",
    state: "Kano",
    lga: "Municipal",
    landmark: "Dawanau Market, grains section, Zone A",
    shopType: "warehouse",
    verified: true,
    rating: 4.5,
    totalSales: 890,
    joinedDate: "2022-10-01",
    avatar: "🌾",
  },
  "seller-25": {
    id: "seller-25",
    name: "Mrs. Funke Adeyemi",
    shopName: "Kids Paradise",
    phone: "+234 709 234 5678",
    whatsapp: "+2347092345678",
    email: "kids.paradise@gmail.com",
    address: "Shop 15, Tejuosho Market, Yaba",
    city: "Lagos",
    state: "Lagos",
    lga: "Lagos Mainland",
    landmark: "Tejuosho Market, 2nd floor, kids section",
    shopType: "shop",
    verified: true,
    rating: 4.7,
    totalSales: 1234,
    joinedDate: "2023-01-20",
    avatar: "🎒",
  },
  "seller-26": {
    id: "seller-26",
    name: "Coach Tunde",
    shopName: "FitGear NG",
    phone: "+234 801 345 6789",
    whatsapp: "+2348013456789",
    email: "fitgear.ng@gmail.com",
    address: "45 Awolowo Road, Ikoyi",
    city: "Lagos",
    state: "Lagos",
    lga: "Eti-Osa",
    landmark: "Beside Ikoyi Club, Awolowo Road",
    shopType: "shop",
    verified: true,
    rating: 4.5,
    totalSales: 345,
    joinedDate: "2023-06-01",
    avatar: "💪",
  },
  "seller-27": {
    id: "seller-27",
    name: "Hajia Zainab",
    shopName: "Abuja Homes",
    phone: "+234 802 456 7890",
    whatsapp: "+2348024567890",
    email: "abuja.homes@gmail.com",
    address: "Suite 101, Dantata Plaza, Gwarinpa",
    city: "Abuja",
    state: "FCT",
    lga: "Gwarinpa",
    landmark: "Dantata Plaza, 1st Avenue, Gwarinpa Estate",
    shopType: "office",
    verified: true,
    rating: 4.3,
    totalSales: 67,
    joinedDate: "2023-08-15",
    avatar: "🏢",
  },
  "seller-28": {
    id: "seller-28",
    name: "Don Carlos",
    shopName: "Prestige Autos",
    phone: "+234 803 567 8901",
    whatsapp: "+2348035678901",
    email: "prestige.autos@gmail.com",
    address: "Adeola Odeku Street, Victoria Island",
    city: "Lagos",
    state: "Lagos",
    lga: "Eti-Osa",
    landmark: "Beside Oriental Hotel, VI",
    shopType: "warehouse",
    verified: true,
    rating: 4.9,
    totalSales: 156,
    joinedDate: "2023-03-01",
    avatar: "🚘",
  },
  "employer-1": {
    id: "employer-1",
    name: "TechCorp Nigeria",
    shopName: "TechCorp Nigeria",
    phone: "+234 700 123 4567",
    whatsapp: "+2347001234567",
    email: "careers@techcorp.ng",
    address: "8 Providence Street, Lekki Phase 1",
    city: "Lagos",
    state: "Lagos",
    lga: "Eti-Osa",
    landmark: "Lekki Phase 1, off Admiralty Way",
    shopType: "office",
    verified: true,
    rating: 4.6,
    totalSales: 0,
    joinedDate: "2023-01-01",
    avatar: "💼",
  },
};

// ── Sample Product Images (using emoji for visual appeal) ──

const PRODUCT_IMAGES: Record<string, string> = {
  vehicles: "🚗",
  electronics: "📱",
  property: "🏠",
  fashion: "👗",
  "home-garden": "🛋️",
  "health-beauty": "💄",
  services: "🔧",
  agriculture: "🌾",
  jobs: "💼",
  "food-drinks": "🍕",
  "kids-baby": "👶",
  "sports-outdoors": "⚽",
};

// ── Category Colors ──

export const CATEGORY_COLORS: Record<string, string> = {
  vehicles: "#3b82f6",
  electronics: "#8b5cf6",
  property: "#10b981",
  fashion: "#ec4899",
  "home-garden": "#f59e0b",
  "health-beauty": "#ef4444",
  services: "#06b6d4",
  agriculture: "#84cc16",
  jobs: "#6366f1",
  "food-drinks": "#f97316",
  "kids-baby": "#a78bfa",
  "sports-outdoors": "#14b8a6",
};

// ── Sample Products Database ──

export const PRODUCTS: Product[] = [
  {
    id: "v-001",
    name: "Toyota Camry (Big Daddy) 2019",
    category: "vehicles",
    subcategory: "cars",
    price: 8500000,
    currency: "NGN",
    condition: "Tokunbo (Belgium)",
    state: "Lagos",
    seller: "Alhaji Motors",
    sellerId: "seller-1",
    image: PRODUCT_IMAGES.vehicles,
    description: "Clean Toyota Camry 2019 model. Full option, leather interior, reverse camera. Buy and drive, no issue.",
    specs: {
      Make: "Toyota",
      Model: "Camry (Big Daddy)",
      Year: "2019",
      Transmission: "Automatic",
      Fuel: "Petrol",
      Mileage: "45,000 km",
      Color: "Black",
      "Custom Duty": "Fully Paid",
    },
    negotiable: true,
    haggleRange: { min: 7500000, max: 8500000 },
    communityDeal: {
      minBuyers: 3,
      discountPercent: 8,
      currentBuyers: 1,
    },
    postedAt: "2h ago",
    views: 234,
  },
  {
    id: "v-002",
    name: "Honda Accord 2020",
    category: "vehicles",
    subcategory: "cars",
    price: 12000000,
    currency: "NGN",
    condition: "Tokunbo (Belgium)",
    state: "Abuja",
    seller: "Capital Auto",
    sellerId: "seller-2",
    image: PRODUCT_IMAGES.vehicles,
    description: "Honda Accord 2020, very clean. Sunroof, push start, full option. Accident free.",
    specs: {
      Make: "Honda",
      Model: "Accord",
      Year: "2020",
      Transmission: "Automatic",
      Fuel: "Petrol",
      Mileage: "32,000 km",
      Color: "White",
    },
    negotiable: true,
    haggleRange: { min: 10500000, max: 12000000 },
    postedAt: "4h ago",
    views: 189,
  },
  {
    id: "v-003",
    name: "Lexus RX 350 (2018)",
    category: "vehicles",
    subcategory: "suv",
    price: 18000000,
    currency: "NGN",
    condition: "Tokunbo (Belgium)",
    state: "Lagos",
    seller: "Prestige Autos",
    sellerId: "seller-28",
    image: PRODUCT_IMAGES.vehicles,
    description: "Lexus RX 350, 2018 model. Full option, panoramic roof, leather seats. Accident-free, clean title.",
    specs: {
      Make: "Lexus",
      Model: "RX 350",
      Year: "2018",
      Transmission: "Automatic",
      Mileage: "58,000 km",
      Color: "Pearl White",
    },
    negotiable: true,
    haggleRange: { min: 16000000, max: 18000000 },
    postedAt: "1d ago",
    views: 456,
  },
  {
    id: "e-001",
    name: "Samsung Galaxy S24 Ultra",
    category: "electronics",
    subcategory: "phones",
    price: 850000,
    currency: "NGN",
    condition: "Brand New",
    state: "Lagos",
    seller: "TechZone NG",
    sellerId: "seller-3",
    image: PRODUCT_IMAGES.electronics,
    description: "Brand new Samsung Galaxy S24 Ultra, 256GB, Titanium Black. Sealed in box with warranty.",
    specs: {
      Brand: "Samsung",
      Model: "Galaxy S24 Ultra",
      Storage: "256GB",
      RAM: "12GB",
      Color: "Titanium Black",
      SIM: "Dual SIM",
    },
    negotiable: true,
    haggleRange: { min: 780000, max: 850000 },
    communityDeal: {
      minBuyers: 5,
      discountPercent: 10,
      currentBuyers: 2,
    },
    postedAt: "30m ago",
    views: 567,
  },
  {
    id: "e-002",
    name: "iPhone 15 Pro Max",
    category: "electronics",
    subcategory: "phones",
    price: 1200000,
    currency: "NGN",
    condition: "London Used",
    state: "Lagos",
    seller: "iStore Computer Village",
    sellerId: "seller-4",
    image: PRODUCT_IMAGES.electronics,
    description: "iPhone 15 Pro Max, 256GB, Natural Titanium. Battery health 94%. Clean with no scratch.",
    specs: {
      Brand: "Apple",
      Model: "iPhone 15 Pro Max",
      Storage: "256GB",
      "Battery Health": "94%",
      Color: "Natural Titanium",
    },
    negotiable: true,
    haggleRange: { min: 1050000, max: 1200000 },
    postedAt: "1h ago",
    views: 890,
  },
  {
    id: "e-003",
    name: 'LG 55" OLED Smart TV',
    category: "electronics",
    subcategory: "tv",
    price: 650000,
    currency: "NGN",
    condition: "Brand New",
    state: "Abuja",
    seller: "ElectroHub",
    sellerId: "seller-5",
    image: PRODUCT_IMAGES.electronics,
    description: 'LG 55" C3 OLED Smart TV. 4K, WebOS, Dolby Atmos. Brand new with 2-year warranty.',
    specs: {
      Brand: "LG",
      Size: '55"',
      Display: "OLED",
      Resolution: "4K UHD",
      "Smart TV": "WebOS",
    },
    negotiable: true,
    haggleRange: { min: 580000, max: 650000 },
    postedAt: "5h ago",
    views: 234,
  },
  {
    id: "e-004",
    name: "Tecno Spark 20 Pro",
    category: "electronics",
    subcategory: "phones",
    price: 45000,
    currency: "NGN",
    condition: "Brand New",
    state: "Lagos",
    seller: "PhoneHub NG",
    sellerId: "seller-16",
    image: PRODUCT_IMAGES.electronics,
    description: "Tecno Spark 20 Pro, 128GB, 8GB RAM. Brand new with 1-year warranty. Great camera and battery life.",
    specs: {
      Brand: "Tecno",
      Model: "Spark 20 Pro",
      Storage: "128GB",
      RAM: "8GB",
      "Battery": "5000mAh",
      Color: "Midnight Black",
    },
    negotiable: true,
    haggleRange: { min: 38000, max: 45000 },
    communityDeal: {
      minBuyers: 8,
      discountPercent: 12,
      currentBuyers: 3,
    },
    postedAt: "45m ago",
    views: 1234,
  },
  {
    id: "e-005",
    name: "Infinix Hot 40i",
    category: "electronics",
    subcategory: "phones",
    price: 38000,
    currency: "NGN",
    condition: "Brand New",
    state: "Abuja",
    seller: "GadgetPoint",
    sellerId: "seller-17",
    image: PRODUCT_IMAGES.electronics,
    description: "Infinix Hot 40i, 128GB, 4GB RAM. Budget-friendly smartphone with fingerprint sensor and good battery.",
    specs: {
      Brand: "Infinix",
      Model: "Hot 40i",
      Storage: "128GB",
      RAM: "4GB",
      "Battery": "5000mAh",
    },
    negotiable: true,
    haggleRange: { min: 32000, max: 38000 },
    postedAt: "3h ago",
    views: 678,
  },
  {
    id: "e-006",
    name: "Oraimo PowerBank 20000mAh",
    category: "electronics",
    subcategory: "accessories",
    price: 8500,
    currency: "NGN",
    condition: "Brand New",
    state: "Lagos",
    seller: "AccessoryZone",
    sellerId: "seller-18",
    image: PRODUCT_IMAGES.electronics,
    description: "Oraimo 20000mAh power bank. Fast charging, dual USB output. Compact and portable.",
    specs: {
      Brand: "Oraimo",
      Capacity: "20000mAh",
      Output: "Dual USB",
      Weight: "350g",
    },
    negotiable: true,
    haggleRange: { min: 7000, max: 8500 },
    communityDeal: {
      minBuyers: 20,
      discountPercent: 15,
      currentBuyers: 8,
    },
    postedAt: "20m ago",
    views: 3456,
  },
  {
    id: "p-001",
    name: "3-Bed Detached Duplex, Lekki Phase 1",
    category: "property",
    subcategory: "houses",
    price: 4500000,
    currency: "NGN",
    condition: "New Build",
    state: "Lagos",
    seller: "Prime Properties NG",
    sellerId: "seller-6",
    image: PRODUCT_IMAGES.property,
    description: "3-bedroom detached duplex in a serviced estate in Lekki Phase 1. BQ, pool, gym, 24/7 power.",
    specs: {
      Type: "Detached Duplex",
      Bedrooms: "3",
      Bathrooms: "4",
      "Rent/Year": "₦4.5M",
      Furnishing: "Semi-Furnished",
      Parking: "2-car garage",
      Power: "Prepaid Meter + Solar",
    },
    negotiable: true,
    haggleRange: { min: 3800000, max: 4500000 },
    postedAt: "2d ago",
    views: 345,
  },
  {
    id: "p-002",
    name: "2-Bed Flat, Gwarinpa",
    category: "property",
    subcategory: "flats",
    price: 1800000,
    currency: "NGN",
    condition: "Serviced",
    state: "Abuja",
    seller: "Abuja Homes",
    sellerId: "seller-27",
    image: PRODUCT_IMAGES.property,
    description: "2-bedroom flat in Gwarinpa Estate. Tiled, wardrobes, prepaid meter. Quiet estate with gate.",
    specs: {
      Type: "2-Bed Flat",
      "Rent/Year": "₦1.8M",
      Furnishing: "Unfurnished",
      Power: "Prepaid Meter",
      Gate: "Yes (Security)",
    },
    negotiable: true,
    haggleRange: { min: 1500000, max: 1800000 },
    postedAt: "1d ago",
    views: 234,
  },
  {
    id: "f-001",
    name: "Premium Ankara Fabric (6 yards)",
    category: "fashion",
    subcategory: "ankara",
    price: 15000,
    currency: "NGN",
    condition: "Brand New",
    state: "Lagos",
    seller: "Aso Oke Palace",
    sellerId: "seller-7",
    image: PRODUCT_IMAGES.fashion,
    description: "Premium quality Ankara fabric, 100% cotton. Beautiful African print, 6 yards. Multiple patterns available.",
    specs: {
      Material: "100% Cotton",
      Length: "6 yards",
      Width: "48 inches",
      Pattern: "Assorted",
    },
    negotiable: true,
    haggleRange: { min: 10000, max: 15000 },
    communityDeal: {
      minBuyers: 10,
      discountPercent: 15,
      currentBuyers: 4,
    },
    postedAt: "1h ago",
    views: 789,
  },
  {
    id: "f-002",
    name: "Senator Suit (Custom Tailored)",
    category: "fashion",
    subcategory: "senator",
    price: 35000,
    currency: "NGN",
    condition: "Custom Made",
    state: "Abuja",
    seller: "Chief Tailor",
    sellerId: "seller-8",
    image: PRODUCT_IMAGES.fashion,
    description: "Custom-tailored Senator suit. Premium fabric, perfect fit. 3-day delivery within Abuja.",
    specs: {
      Style: "Senator",
      Fabric: "Premium Chiffon",
      Delivery: "3 days",
      Location: "Abuja",
    },
    negotiable: true,
    haggleRange: { min: 28000, max: 35000 },
    postedAt: "6h ago",
    views: 456,
  },
  {
    id: "f-003",
    name: "Premium Leather Bag (Handmade)",
    category: "fashion",
    subcategory: "bags",
    price: 25000,
    currency: "NGN",
    condition: "Handmade",
    state: "Kano",
    seller: "Kano Leather Works",
    sellerId: "seller-19",
    image: PRODUCT_IMAGES.fashion,
    description: "Handcrafted genuine leather bag. Made in Kano with traditional techniques. Brown, with brass hardware.",
    specs: {
      Material: "Genuine Leather",
      Color: "Brown",
      Hardware: "Brass",
      Origin: "Kano, Nigeria",
    },
    negotiable: true,
    haggleRange: { min: 18000, max: 25000 },
    communityDeal: {
      minBuyers: 6,
      discountPercent: 10,
      currentBuyers: 2,
    },
    postedAt: "12h ago",
    views: 345,
  },
  {
    id: "hg-001",
    name: 'Leather Sofa Set (3+2+1)',
    category: "home-garden",
    subcategory: "furniture",
    price: 280000,
    currency: "NGN",
    condition: "Brand New",
    state: "Lagos",
    seller: "HomeFitters NG",
    sellerId: "seller-9",
    image: PRODUCT_IMAGES["home-garden"],
    description: "Italian leather sofa set. 3-seater + 2-seater + 1-seater. Black, with gold accents. Free delivery within Lagos.",
    specs: {
      Material: "Italian Leather",
      Pieces: "3+2+1",
      Color: "Black/Gold",
      Delivery: "Free (Lagos)",
    },
    negotiable: true,
    haggleRange: { min: 230000, max: 280000 },
    postedAt: "8h ago",
    views: 567,
  },
  {
    id: "hg-002",
    name: "Diesel Generator 3.5KVA",
    category: "home-garden",
    subcategory: "power",
    price: 320000,
    currency: "NGN",
    condition: "Brand New",
    state: "Lagos",
    seller: "PowerTech NG",
    sellerId: "seller-21",
    image: PRODUCT_IMAGES["home-garden"],
    description: "3.5KVA diesel generator with key start. Low noise, fuel efficient. Perfect for home and small office use.",
    specs: {
      Power: "3.5KVA",
      Fuel: "Diesel",
      Start: "Key Start",
      Noise: "Low (65dB)",
    },
    negotiable: true,
    haggleRange: { min: 270000, max: 320000 },
    communityDeal: {
      minBuyers: 5,
      discountPercent: 8,
      currentBuyers: 2,
    },
    postedAt: "3h ago",
    views: 890,
  },
  {
    id: "hb-001",
    name: "Human Hair Wig (Bone Straight 22\")",
    category: "health-beauty",
    subcategory: "hair",
    price: 95000,
    currency: "NGN",
    condition: "Brand New",
    state: "Lagos",
    seller: "Crown Hair Gallery",
    sellerId: "seller-10",
    image: PRODUCT_IMAGES["health-beauty"],
    description: 'Premium bone straight human hair wig, 22 inches. 180% density, 13x4 frontal. Can be styled.',
    specs: {
      Type: "Bone Straight",
      Length: '22"',
      Density: "180%",
      Lace: "13x4 Frontal",
      Origin: "Vietnamese",
    },
    negotiable: true,
    haggleRange: { min: 75000, max: 95000 },
    communityDeal: {
      minBuyers: 5,
      discountPercent: 12,
      currentBuyers: 1,
    },
    postedAt: "40m ago",
    views: 1234,
  },
  {
    id: "hb-002",
    name: "Carrot Glow Skin Set (3-in-1)",
    category: "health-beauty",
    subcategory: "skincare",
    price: 12000,
    currency: "NGN",
    condition: "Brand New",
    state: "Lagos",
    seller: "GlowUp Beauty",
    sellerId: "seller-22",
    image: PRODUCT_IMAGES["health-beauty"],
    description: "Carrot Glow skin lightening set: soap, cream, and serum. Natural ingredients, visible results in 7 days.",
    specs: {
      Type: "3-in-1 Set",
      Ingredients: "Natural Carrot Extract",
      "Skin Type": "All Types",
      Result: "7 Days Visible",
    },
    negotiable: true,
    haggleRange: { min: 9000, max: 12000 },
    postedAt: "2h ago",
    views: 2345,
  },
  {
    id: "sv-001",
    name: "Professional Plumbing Service",
    category: "services",
    subcategory: "plumber",
    price: 15000,
    currency: "NGN",
    condition: "Available Now",
    state: "Lagos",
    seller: "Master Plumbers NG",
    sellerId: "seller-11",
    image: PRODUCT_IMAGES.services,
    description: "Licensed plumber with 15+ years experience. Pipe fitting, bathroom installation, water heater, septic tank. Same-day service.",
    specs: {
      Experience: "15+ years",
      Availability: "Same Day",
      Certification: "Licensed & Insured",
      Coverage: "Lagos Mainland & Island",
    },
    negotiable: true,
    haggleRange: { min: 8000, max: 15000 },
    postedAt: "1h ago",
    views: 567,
  },
  {
    id: "sv-002",
    name: "Event DJ & Sound System (Full Package)",
    category: "services",
    subcategory: "dj",
    price: 200000,
    currency: "NGN",
    condition: "Available Now",
    state: "Lagos",
    seller: "DJ SoundMax",
    sellerId: "seller-23",
    image: PRODUCT_IMAGES.services,
    description: "Complete event DJ package: 2 speakers, mixer, mic, DJ for 6 hours. Owambe, wedding, birthday, corporate.",
    specs: {
      Duration: "6 hours",
      Equipment: "Full Sound System",
      Mic: "2 Wireless Mics",
      Coverage: "Lagos & Ogun",
    },
    negotiable: true,
    haggleRange: { min: 150000, max: 200000 },
    postedAt: "5h ago",
    views: 345,
  },
  {
    id: "ag-001",
    name: "Noiler Birds (Day-Old Chicks, 100 pieces)",
    category: "agriculture",
    subcategory: "poultry",
    price: 55000,
    currency: "NGN",
    condition: "Live",
    state: "Ibadan",
    seller: "GreenFarm Agro",
    sellerId: "seller-12",
    image: PRODUCT_IMAGES.agriculture,
    description: "Quality Noiler day-old chicks. Fast-growing, disease-resistant. 100 pieces per carton. Vaccinated.",
    specs: {
      Type: "Noiler",
      Age: "Day-Old",
      Quantity: "100 pieces",
      Vaccination: "Day 1 (Marek + Newcastle)",
    },
    negotiable: true,
    haggleRange: { min: 45000, max: 55000 },
    communityDeal: {
      minBuyers: 8,
      discountPercent: 10,
      currentBuyers: 3,
    },
    postedAt: "4h ago",
    views: 678,
  },
  {
    id: "ag-002",
    name: "50kg Bags of Rice (Premium)",
    category: "agriculture",
    subcategory: "grains",
    price: 55000,
    currency: "NGN",
    condition: "Fresh",
    state: "Kano",
    seller: "Savanna Farms",
    sellerId: "seller-24",
    image: PRODUCT_IMAGES.agriculture,
    description: "Premium long grain rice, 50kg bag. Stone-free, well-processed. Direct from the farm.",
    specs: {
      Weight: "50kg",
      Type: "Long Grain",
      Quality: "Stone-Free",
      Origin: "Kano",
    },
    negotiable: true,
    haggleRange: { min: 48000, max: 55000 },
    communityDeal: {
      minBuyers: 10,
      discountPercent: 12,
      currentBuyers: 4,
    },
    postedAt: "6h ago",
    views: 1234,
  },
  {
    id: "j-001",
    name: "Senior Frontend Developer (Remote)",
    category: "jobs",
    subcategory: "remote",
    price: 600000,
    currency: "NGN",
    condition: "Full-Time",
    state: "Remote",
    seller: "TechCorp Nigeria",
    sellerId: "employer-1",
    image: PRODUCT_IMAGES.jobs,
    description: "Senior Frontend Developer role. React, Next.js, TypeScript. Fully remote. ₦600K - ₦1M/month.",
    specs: {
      Position: "Senior Frontend Developer",
      Company: "TechCorp Nigeria",
      Salary: "₦600K - ₦1M/mo",
      Mode: "Remote",
      Experience: "5+ years",
    },
    negotiable: false,
    haggleRange: { min: 600000, max: 1000000 },
    postedAt: "2h ago",
    views: 2345,
  },
  {
    id: "fd-001",
    name: "Jollof Rice Catering (100 guests)",
    category: "food-drinks",
    subcategory: "catering",
    price: 150000,
    currency: "NGN",
    condition: "Prepared (Ready to Eat)",
    state: "Lagos",
    seller: "Mama Calabar Kitchen",
    sellerId: "seller-13",
    image: PRODUCT_IMAGES["food-drinks"],
    description: "Premium Owambe catering for 100 guests. Jollof rice, fried rice, moi moi, salad, assorted meats, dodo. Chafing dishes included.",
    specs: {
      Serving: "100 guests",
      Package: "Owambe Standard",
      Dishes: "6 items",
      Setup: "Chafing dishes included",
    },
    negotiable: true,
    haggleRange: { min: 120000, max: 150000 },
    postedAt: "3h ago",
    views: 456,
  },
  {
    id: "fd-002",
    name: "Zobo Drink (5 litres)",
    category: "food-drinks",
    subcategory: "drinks-bev",
    price: 3500,
    currency: "NGN",
    condition: "Fresh",
    state: "Lagos",
    seller: "Aunty Zobo",
    sellerId: "seller-20",
    image: PRODUCT_IMAGES["food-drinks"],
    description: "Fresh Zobo drink, 5 litres. Made with hibiscus, ginger, pineapple. No preservatives. Order before 12pm for same-day delivery.",
    specs: {
      Size: "5 litres",
      Type: "Zobo (Hibiscus)",
      Preservatives: "None",
      Delivery: "Same-day (Lagos)",
    },
    negotiable: true,
    haggleRange: { min: 2800, max: 3500 },
    postedAt: "15m ago",
    views: 5678,
  },
  {
    id: "kb-001",
    name: "Baby Stroller (Travel System)",
    category: "kids-baby",
    subcategory: "baby-gear",
    price: 120000,
    currency: "NGN",
    condition: "Brand New",
    state: "Lagos",
    seller: "BabyWorld NG",
    sellerId: "seller-15",
    image: PRODUCT_IMAGES["kids-baby"],
    description: "3-in-1 baby travel system. Stroller + car seat + bassinet. Lightweight, foldable. Suitable from birth to 3 years.",
    specs: {
      Type: "3-in-1 Travel System",
      Weight: "8.5 kg",
      "Age Range": "0-3 years",
      Color: "Grey/Navy",
    },
    negotiable: true,
    haggleRange: { min: 95000, max: 120000 },
    postedAt: "2h ago",
    views: 678,
  },
  {
    id: "kb-002",
    name: "Children's School Bag Set (3 pcs)",
    category: "kids-baby",
    subcategory: "school",
    price: 8500,
    currency: "NGN",
    condition: "Brand New",
    state: "Lagos",
    seller: "Kids Paradise",
    sellerId: "seller-25",
    image: PRODUCT_IMAGES["kids-baby"],
    description: "3-piece school bag set: backpack, lunch bag, pencil case. Durable, water-resistant. Ages 4-12.",
    specs: {
      Pieces: "3 (Bag + Lunch + Pencil)",
      Material: "Water-Resistant Nylon",
      "Age Range": "4-12 years",
      Designs: "Assorted Cartoon",
    },
    negotiable: true,
    haggleRange: { min: 6000, max: 8500 },
    postedAt: "1h ago",
    views: 901,
  },
  {
    id: "sp-001",
    name: "Chelsea FC Home Jersey 24/25",
    category: "sports-outdoors",
    subcategory: "jerseys",
    price: 18000,
    currency: "NGN",
    condition: "Brand New",
    state: "Lagos",
    seller: "SportsHub NG",
    sellerId: "seller-14",
    image: PRODUCT_IMAGES["sports-outdoors"],
    description: "Chelsea FC Home Jersey 24/25 season. Official Nike product. All sizes available.",
    specs: {
      Brand: "Nike",
      Team: "Chelsea FC",
      Season: "24/25",
      Sizes: "S to XXL",
    },
    negotiable: true,
    haggleRange: { min: 14000, max: 18000 },
    communityDeal: {
      minBuyers: 15,
      discountPercent: 20,
      currentBuyers: 6,
    },
    postedAt: "1h ago",
    views: 1234,
  },
  {
    id: "sp-002",
    name: "Adjustable Dumbbell Set (20kg)",
    category: "sports-outdoors",
    subcategory: "fitness",
    price: 45000,
    currency: "NGN",
    condition: "Brand New",
    state: "Lagos",
    seller: "FitGear NG",
    sellerId: "seller-26",
    image: PRODUCT_IMAGES["sports-outdoors"],
    description: "Adjustable dumbbell set, 20kg total. Quick-change weight plates. Perfect for home gym.",
    specs: {
      Weight: "20kg Total",
      Type: "Adjustable",
      Material: "Chrome + Rubber",
      "Weight Plates": "8 pieces",
    },
    negotiable: true,
    haggleRange: { min: 36000, max: 45000 },
    postedAt: "4h ago",
    views: 456,
  },
];

// ── Helper Functions ──

export function formatPrice(price: number): string {
  return `₦${price.toLocaleString("en-NG")}`;
}

export function searchProducts(query: string): Product[] {
  const q = query.toLowerCase().trim();

  if (!q) return [];

  return PRODUCTS.filter((p) => {
    const searchable = [
      p.name,
      p.category,
      p.subcategory,
      p.condition,
      p.state,
      p.seller,
      p.description,
      ...Object.values(p.specs),
    ]
      .join(" ")
      .toLowerCase();

    return (
      searchable.includes(q) ||
      q.split(" ").every((word) => searchable.includes(word))
    );
  });
}

export function getProductsByCategory(category: string): Product[] {
  return PRODUCTS.filter((p) => p.category === category);
}

export function getProductsByPriceRange(min: number, max: number): Product[] {
  return PRODUCTS.filter((p) => p.price >= min && p.price <= max);
}

export function getProductsUnderPrice(maxPrice: number): Product[] {
  return PRODUCTS.filter((p) => p.price <= maxPrice);
}

export function getProductById(id: string): Product | undefined {
  return PRODUCTS.find((p) => p.id === id);
}

export function getSellerById(sellerId: string): Seller | undefined {
  return SELLERS[sellerId];
}

export function getCommunityDeals(): Product[] {
  return PRODUCTS.filter((p) => p.communityDeal);
}

// ── Category Names ──

export const CATEGORY_LABELS: Record<string, string> = {
  vehicles: "Vehicles",
  electronics: "Electronics",
  property: "Property",
  fashion: "Fashion",
  "home-garden": "Home & Garden",
  "health-beauty": "Health & Beauty",
  services: "Services",
  agriculture: "Agriculture",
  jobs: "Jobs",
  "food-drinks": "Food & Drinks",
  "kids-baby": "Kids & Baby",
  "sports-outdoors": "Sports & Outdoors",
};

export const CATEGORY_ICONS: Record<string, string> = {
  vehicles: "🚗",
  electronics: "📱",
  property: "🏠",
  fashion: "👗",
  "home-garden": "🛋️",
  "health-beauty": "💄",
  services: "🔧",
  agriculture: "🌾",
  jobs: "💼",
  "food-drinks": "🍕",
  "kids-baby": "👶",
  "sports-outdoors": "⚽",
};

// ── Category Descriptions ──

export const CATEGORY_DESCRIPTIONS: Record<string, string> = {
  vehicles: "Cars, SUVs, motorcycles & more — find your next ride",
  electronics: "Phones, laptops, TVs & gadgets — tech that moves you",
  property: "Houses, flats, land & offices — your space awaits",
  fashion: "Ankara, Senator, bags & shoes — wear your culture",
  "home-garden": "Furniture, generators & decor — make it home",
  "health-beauty": "Hair, skincare & wellness — look & feel your best",
  services: "Plumbers, DJs, tutors & more — skilled hands at work",
  agriculture: "Poultry, grains & farming — from the soil to you",
  jobs: "Remote, full-time & contract — your next gig",
  "food-drinks": "Catering, Zobo & snacks — taste the market",
  "kids-baby": "Strollers, bags & toys — for the little ones",
  "sports-outdoors": "Jerseys, fitness & gear — play hard",
};
